export const MAP_LAYER_EARTHQUAKE = {
  id: 'earthquakes',
  type: 'circle',
  source: 'earthquakes',
  paint: {
    'circle-color': [
      'step',
      ['get', 'magnitude'],
      ['to-color', '#0096FF'],
      2.5,
      ['to-color', '#FFFF00'],
      5.5,
      ['to-color', '#FF9500'],
      7.0,
      ['to-color', '#FF0000'],
    ],
    'circle-radius': [
      'interpolate',
      ['linear'],
      ['zoom'],
      1,
      0,
      5,
      ['step', ['get', 'magnitude'], 2, 2.5, 3, 5.5, 4, 7.0, 6],
      10,
      ['step', ['get', 'magnitude'], 7, 2.5, 8, 5.5, 9, 7.0, 11],
      15,
      ['step', ['get', 'magnitude'], 12, 2.5, 13, 5.5, 14, 7.0, 16],
    ],
    'circle-opacity': [
      'interpolate',
      ['linear'],
      ['zoom'],
      0,
      0.1,
      5,
      ['step', ['get', 'magnitude'], 0.3, 2.5, 0.4, 5.5, 0.6, 7.0, 0.7],
      10,
      ['step', ['get', 'magnitude'], 0.5, 2.5, 0.6, 5.5, 0.8, 7.0, 0.9],
    ],
    // 'circle-stroke-color': '#FFFFFF',
    // 'circle-stroke-color': '#FFFFFF',
    // 'circle-stroke-opacity': [
    //   'interpolate',
    //   ['linear'],
    //   ['zoom'],
    //   0,
    //   0.1,
    //   4,
    //   0.3,
    //   10,
    //   0.75,
    // ],
    // 'circle-stroke-width': [
    //   'interpolate',
    //   ['linear'],
    //   ['zoom'],
    //   3,
    //   0,
    //   4,
    //   0.5,
    //   10,
    //   1,
    // ],
  },
  layout: {
    visibility: 'visible',
    'circle-sort-key': ['get', 'magnitude'],
  },
};
