export const MAP_LAYER_EARTHQUAKE = {
  id: 'earthquakes',
  type: 'circle',
  source: 'earthquakes',
  paint: {
    'circle-color': [
      'step',
      ['get', 'magnitude'],
      '#0096FF',
      2.5,
      '#FFFF00',
      5.5,
      '#FF9500',
      7.0,
      '#FF0000',
    ],
    'circle-radius': [
      'interpolate',
      ['linear'],
      ['zoom'],
      1,
      0,
      5,
      4,
      10,
      8,
      15,
      12,
    ],
    'circle-opacity': [
      'interpolate',
      ['linear'],
      ['zoom'],
      0,
      0.1,
      4,
      0.3,
      10,
      0.75,
    ],
    'circle-stroke-color': '#FFFFFF',
    'circle-stroke-opacity': [
      'interpolate',
      ['linear'],
      ['zoom'],
      0,
      0.1,
      4,
      0.3,
      10,
      0.75,
    ],
    'circle-stroke-width': [
      'interpolate',
      ['linear'],
      ['zoom'],
      3,
      0,
      4,
      0.5,
      10,
      1,
    ],
  },
  layout: {
    visibility: 'visible',
    'circle-sort-key': ['get', 'magnitude'],
  },
};
